permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: developing woot
description: "A free Jekyll theme"
email: developingwoot@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com"
url: "http://developingwoot.io"
repository: "https://github.com/developingwoot"
disqus_shortname: "https-developingwoot-github-io"
google_analytics: UA-82756077-1

# social footer
social:
  github:
    slug: github
    link: http://github.com/developingwoot
  # facebook:
  #   slug: facebook
  #   link: http://facebook.com/fernando.dev
  twitter:
    slug: twitter
    link: http://twitter.com/developingwoot
  # instagram:
  #   slug: instagram
  #   link: http://instagram.com/nandomoreira.me
  # linkedin:
  #   slug: linkedin
  #   link: http://linkedin.com/in/nandomoreirame