# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#gems
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-seo-tag

# Site settings
title: Developing Woot
email: developingwoot@gmail.com
description: A simple Jekyll blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://developingwoot.github.io" # the base hostname & protocol for your site
twitter_username: developingwoot
github_username:  developingwoot
timezone: America/New_York
repo: "https://github.com/developingwoot"
disqus_shortname: "https-developingwoot-github-io"
google_analytics: UA-82756077-1
username: developingwoot

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

include: ['_pages']