# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#gems
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-seo-tag

# Site settings
title: Developing Woot
email: developingwoot@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I love tacos and writing code.  I wanted to start a blog that I could
  truly say is mine, while keeping it as free as possible.  This blog is 
  my story to blog freely about code and tacos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://developingwoot.github.io" # the base hostname & protocol for your site
twitter_username: developingwoot
github_username:  developingwoot
timezone: America/New_York

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

include: ['_pages']